// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyeymuklsnbgfiohqncg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZXltdWtsc25iZ2Zpb2hxbmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzU2NTQsImV4cCI6MjA1ODUxMTY1NH0.wLS-IlgZuobbWqTgzORgvfFemhgitVEMQgGJ-fFJkC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);